database:
  host:       'localhost'
  user:       'root'
  password:   'root'
  database:   'NOMPRENOMSUJET_BD_104_V1'
  port:       3306
  mysql_bin_path: '' #(OPTIONAL database backup) Only if you are using external applications for mysql server as (MAMP, UwAmp, XAMPP...)
                     # With these we can do the backup of the database

server:
  address:    '127.0.0.1'
  port:       '8000'
  secret_key: 'My_Secret_Key'
  debug:       True
