database:
  host:       'localhost'
  user:       'root'
  password:   'root'
  database:   'NOMPRENOMSUJET_BD_104_V1'
  port:       3306
  mysql_bin_path: '' #(OPTIONAL database backup) for (MAMP, UwAmp, XAMPP...)
                     # Is the path of your mysql bin folder
                     # Example: 'C:\MAMP\bin\mysql\bin'

server:
  address:    '127.0.0.1'
  port:       '8000'
  secret_key: 'My_Secret_Key'
  debug:       True
